//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Web;
    using System.Collections.Generic;
    public partial class property
    {
        public int Id { get; set; }
        public string propertytype { get; set; }
        public string location { get; set; }
        public string area { get; set; }
        public string category { get; set; }
        public string selltype { get; set; }
        public Nullable<decimal> demand { get; set; }
        public string lease { get; set; }
        public string sublease { get; set; }
        public Nullable<byte> room { get; set; }
        public string propertyimage { get; set; }

        public HttpPostedFileBase imageayi { get; set; }
    }
}
